### ISSUE TITLE
Windows CMD - PORT command doesn't exist

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [parkr/ping#2]
@parkr 

----

Can not run this command on Windows 10:

    PORT=8972 PING_DB=user:passwd@localhost/ping ping

**Comment by parkr** [comment]
Hey @SuriyaaKudoIsc!

This project documentation is written with Unix systems in mind. I don't know how to use the Windows command prompt. In the case of the above command you posted, you have to set the variable `PORT` to `8972` in the environment. Same with `PING_DB`. They're two environment variables.

If you can write up some documentation on how to set environment variables in the command prompt on Windows, I would gladly accept it! Thanks!

**Comment by SuriyaaKudoIsc** [comment]
@parkr 

----

#### Requirements on Windows
* I use MariaDB:

```bash
C:\Users\Suriyaa>mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 31
Server version: 10.0.21-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW VARIABLES LIKE "%version%";
+-------------------------+---------------------------------+
| Variable_name           | Value                           |
+-------------------------+---------------------------------+
| innodb_version          | 5.6.25-73.1                     |
| protocol_version        | 10                              |
| slave_type_conversions  |                                 |
| version                 | 10.0.21-MariaDB                 |
| version_comment         | mariadb.org binary distribution |
| version_compile_machine | AMD64                           |
| version_compile_os      | Win32                           |
| version_malloc_library  | system                          |
+-------------------------+---------------------------------+
8 rows in set (0.00 sec)

MariaDB [(none)]>
```

----

#### Setup
And I set already:
* `PORT` as an environment variable to `8972`.
* `PING_DB` to `C:\Go\work\src\github.com\parkr\ping\database.go`.

* Create also the `ODBC` user in phpMyAdmin (run mysql command without passwort asking and errors!)

----

#### Results
* :white_check_mark: Run with success:
```bash
> go get github.com/parkr/ping
> mysql -e 'create database ping;'
```

* :exclamation: Still failed to run `PORT=8972 PING_DB=user:passwd@localhost/ping ping` with my username and password.

**Comment by parkr** [comment]
`PING_DB` should not be set to `C:\Go\work\src\github.com\parkr\ping\database.go`, it should be set to the connection string to your MySQL instance. I don't know if it is compatible with MariaDB.

**Comment by SuriyaaKudoIsc** [comment]
@parkr How does `PING_DB` looks like for example?
