### ISSUE TITLE
Logging format

### ISSUE THREAD

**Issue by jrasanen** [parkr/ping#6]
Hi,

I suggest changing the logging format to something more sensible.

Maybe take an example from Nginx/Apache access logs, most web-servers use the same format:

```127.0.0.1 - - [22/Jun/2016:23:42:04 +0300] "GET / HTTP/1.1" 200 101 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"```

**Comment by parkr** [comment]
I use a reverse proxy (nginx) so I don't need access logs like this because nginx writes them out for me. `goji` used to provide them, but I just switched them off when I removed goji (#5). How have you deployed `ping`?

**Comment by parkr** [comment]
I will most likely use some form of [technoweenie/grohl](https://github.com/technoweenie/grohl#usage), because key-value pairs are easier to parse and search.

**Comment by jrasanen** [comment]
Deployed with supervisord. Nginx and reverse proxy could be a far better idea.

**Comment by parkr** [comment]
@jrasanen Is there a reason you want access logs, out of curiosity?

**Comment by jrasanen** [comment]
@parkr Gave it a thought yesterday and log's aren't needed, as they can be done with a reverse proxy, which probably should be the preferred way to run this in production.

Where they could be needed is to debug odd behaviour if somebody tries to inject false data / cause an overflow.

In my opinion this issue can be closed.

**Comment by parkr** [comment]
Sounds good! The process will likely panic in that case, so you should see output then.
