### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jrasanen** [parkr/ping#7]
Would be good to have at least some test coverage. I'd be glad to contribute and sharpen my Go skills.

**Comment by jrasanen** [comment]
I also feel like tests shouldn't depend on MySQL installation, but to implement SQLite support the project needs some rework for that to be possible.

**Comment by parkr** [comment]
@jrasanen Yeah, getting a test setup in there would be great! Mocking SQL calls is fine. I don't want to get too complicated, but I would be OK supporting SQLite and MySQL. Start with some tests for the ping handler's error states (shouldn't hit the DB) and go from there. You can create a DB interface which contains our required methods and have a MySQL adapter that is default.

**Comment by parkr** [comment]
😄  Thank you!
