### ISSUE TITLE
Respect Global Privacy Control header

### ISSUE THREAD

**Issue by fredster33** [parkr/ping#76]
Global Privacy Control is a new header (`Sec-GPC: 1`) that aims to replace Do Not Track. It's currently supported in Firefox and Brave, as well as a few extensions :)

Links:
* https://globalprivacycontrol.org/
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-GPC
* https://privacycg.github.io/gpc-spec/

**Comment by parkr** [comment]
Looks like it's not yet on the standards track. From the Mozilla website:

> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

**Comment by parkr** [comment]
My browser (Brave) does support this, and was announced in 2020: https://brave.com/web-standards-at-brave/4-global-privacy-control/

**Comment by parkr** [comment]
#77 implements this.

It skips the `.well-known/gpc.json` file, but that could be easily added in the future if it became a `MUST`.
